INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

INCLUDEPATH += $$PWD/Globals

INCLUDEPATH += $$PWD/NativeWindow

INCLUDEPATH += $$PWD/Layouts
INCLUDEPATH += $$PWD/Controls
INCLUDEPATH += $$PWD/Containers
INCLUDEPATH += $$PWD/DockSystem
